default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: postgres

test:
  url: postgres://database_9p16_user:GFOnVVVvTW18d7ctSUrEeaJ6J1KfIePa@dpg-cn5kbef109ks739us3pg-a/database_9p16
  <<: *default
  database: postgres

production:
  url: postgres://database_9p16_user:GFOnVVVvTW18d7ctSUrEeaJ6J1KfIePa@dpg-cn5kbef109ks739us3pg-a/database_9p16
  <<: *default
  database: postgres
  username: root
  password: root
